name: tag-discounts
on: [workflow_dispatch]

env:
  CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Discounts
        uses: actions/checkout@v3
      - name: Run tests 🧪
        uses: cypress-io/github-action@v6
        with:
          record: true  
          env: grepTags=discounts
          tag: discounts-suite